title: Smartion
name: Smartion 
email: contacto.innovaccionmx@gmail.com
description: INTELIGENCIA + INNOVACIÓN

baseurl: ""
url: ""

display_footer: inital  #change this to 'none' if you want to hide the footer copyright text

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

project_one: Asesoría para la innovación
project_one_description: >
  Asesoría personalizada para incorparar soluciones 
  innovadoras a problemáticas específicas de las Micro, 
  Pequeñas y Medianas empresas mexicanas.
project_one_url: https://www.facebook.com/commerce/products/1992138404143578/
project_one_icon: location_on

project_two: Consultoría para la innovación
project_two_description: >
  Consultoría para el desarrollo de soluciones(productos,
  servicios y procesos) basadas en innovación. 
  Cada consultoría se ajustará a las necesidades y 
  características del producto, del cliente y del mercado, 
  con el acompañamiento de expertos en generación de proyectos 
  de innovación.
project_two_url: https://www.facebook.com/commerce/products/769656966491320/
project_two_icon: hotel


project_three: Capacitación para la innovación
project_three_description: >
 Capacitación a grupos de máximo 15 personas, 
 para alinear el diseño y la implementación de 
 estrategias basadas en innovación, en proyectos dentro de las empresas
project_three_url: https://www.facebook.com/commerce/products/1763683810416991/
project_three_icon: hotel


project_four: Dictaminación de viabilidad para proyectos de innovación
project_four_description: >
 Revisión, corrección y dictaminación de la 
 viabilidad y rentabilidad de proyectos basados en 
 innovación científica y tecnológica para su implementación, 
 o presentación a inversionistas públicos y privados.
project_four_url: https://www.facebook.com/commerce/products/1486995961406390/
project_four_icon: hotel

project_five: Matching innovación y soluciones
project_five_description: >
  Vinculación de empresas o instituciones públicas y/o privadas con alguna problemática, 
  con propuestas de solución generadas por expertos en cada materia, basadas en innovación, 
  ciencia y tecnología aplicada.
project_five_url: https://www.facebook.com/commerce/products/1766585696743021/
project_five_icon: restaurant

portfolio_heading: Servicios
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: amazonwebservices
  - name: android
  - name: angularjs
  - name: apache
  - name: appcelerator
  - name: apple
  - name: atom
  - name: babel
  - name: backbonejs
  - name: bitbucket
  - name: bootstrap


icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Eshop

github: https://www.facebook.com/SmartionMx/?ref=br_rs
medium: https://medium.com


# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: none # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
